"""Add comments column

Revision ID: 1002728ce08e
Revises: cf290e6de38d
Create Date: 2024-07-16 03:32:46.100014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1002728ce08e'
down_revision = 'cf290e6de38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('exercise_checked',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('medicine_checked',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('medicine_checked',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('exercise_checked',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
