"""Add comments column to yow

Revision ID: 26a0683cbea9
Revises: 1002728ce08e
Create Date: 2024-07-16 03:39:15.850686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a0683cbea9'
down_revision = '1002728ce08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('exercise_checked',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('medicine_checked',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('medicine_checked',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('exercise_checked',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
