"""my changes example message

Revision ID: 48e22c924c59
Revises: 6b1113f848d5
Create Date: 2024-05-23 01:08:34.746666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e22c924c59'
down_revision = '6b1113f848d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acc_type', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('acc_type')

    # ### end Alembic commands ###
