"""initial migration

Revision ID: 5a7dbfee6d90
Revises: 26a0683cbea9
Create Date: 2024-07-16 07:15:28.581463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7dbfee6d90'
down_revision = '26a0683cbea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cancer_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('cancer_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
