"""francis changes

Revision ID: 6b1113f848d5
Revises: 
Create Date: 2024-05-22 23:36:42.634741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1113f848d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('municipality', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('municipality')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
