"""Add comments column to Users

Revision ID: cf290e6de38d
Revises: f1739d956f3b
Create Date: 2024-07-16 03:17:11.383472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf290e6de38d'
down_revision = 'f1739d956f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('medicine_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('medicine_checked')
        batch_op.drop_column('exercise_checked')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('exercise_checked', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('medicine_checked', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('medicine_checked')
        batch_op.drop_column('exercise_checked')

    # ### end Alembic commands ###
