"""Description of the migratiodsdsdsdsd

Revision ID: e3d947406067
Revises: 38cdd88a9575
Create Date: 2024-07-31 01:29:32.697090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d947406067'
down_revision = '38cdd88a9575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('itemname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('stocks', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
