"""Add comments column to Users

Revision ID: f1739d956f3b
Revises: 4e38e180ca5e
Create Date: 2024-07-16 02:00:23.597395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1739d956f3b'
down_revision = '4e38e180ca5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('medicine_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('medicine_checked')
        batch_op.drop_column('exercise_checked')

    # ### end Alembic commands ###
